Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,13 +1,15 @@
 #!/bin/bash 
 
 
-#      ▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
-#      ▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
-#      ▇▇          ▇ @hlh313   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
-#      ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @hlh313
-#      ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @hlh_313  ▇▄                 ▇▇                 ▇▇
-#      ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source TH3max BY @hlh_313
-#---------------------------------------------------------------------
+
+#█ █ █ █ █   █                        █       █                                 █  █             █ █ █ █ █
+#█                      █                                   █                              █          █        █                █
+#█                      █                        █       █                           █                █     █             █
+#█ █ █ █ █   █ █ █ █ █    █       █ █ █ █ █       █                 █     █ █ █ █  
+#                   █   █                 █   █       █                █      █ █  █  █ █     █            █
+#                   █   █                 █   █       █                █      █                  █     █               █
+#█ █ █ █ █   █                █    █       █                █      █                  █     █ █ █ █ █ 
+
 cd $(cd $(dirname $0); pwd)
  
 RED='\033[0;31m'
@@ -22,16 +24,17 @@ Version=`lsb_release -rs | cut -f1 -d"."`
 
 if [ "$Version" == "18" ];then
 echo -e "${GREEN}
-▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
-▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
-▇▇          ▇ @hlh313   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
-▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @hlh313
-▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @hlh_313  ▇▄                 ▇▇                 ▇▇
-▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source TH3max BY @hlh_313
+█ █ █ █ █   █                        █       █                                 █  █             █ █ █ █ █
+█                      █                                   █                              █          █        █                █
+█                      █                        █       █                           █                █     █             █
+█ █ █ █ █   █ █ █ █ █    █       █ █ █ █ █       █                 █     █ █ █ █  
+                   █   █                 █   █       █                █      █ █  █  █ █     █            █
+                   █   █                 █   █       █                █      █                  █     █               █
+█ █ █ █ █   █                █    █       █                █      █                  █     █ █ █ █ █ 
 ----------------------------------------------------------------------${CNIL}"
 echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
 ${CNIL}";
-echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source Th3max 
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source Th3shihab 
 ${CNIL}";
 exit;
 fi
@@ -41,7 +44,7 @@ if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source TH3max${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source TH3shihab${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
@@ -70,10 +73,10 @@ sudo rm -fr ../.telegram-cli
 done
 else
 
-if ! screen -list | grep -q "max"; then
-screen -S max ./run R
+if ! screen -list | grep -q "shihab"; then
+screen -S shihab ./run R
 fi
-screen -X -S max kill
-screen -S max ./run R
+screen -X -S shihab kill
+screen -S shihab ./run R
 fi
 
